import type { NextPage } from 'next';
import { Text, Flex } from '@chakra-ui/react';
import TopBar from '../components/TopBar';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <Flex minH="100vh" direction="column">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <TopBar />
      <Flex as="main" flex={1}>
        <div>
          <Text>abcdefg</Text>
        </div>
      </Flex>

      <footer></footer>
    </Flex>
  );
};

export default Home;
